#!/bin/bash
#
# Generate OpenGL function stubs from Mesa's libGL
# This extracts all gl* symbols and creates forwarding functions
#

echo "========================================="
echo "  OpenGL Stub Generator"
echo "========================================="

# SSH to VM and extract symbols from Mesa
echo "📡 Extracting OpenGL symbols from Mesa libGL on VM..."
# Extract gl* symbols but exclude glX* (GLX functions are in glx_wrapper.c)
SYMBOLS=$(ssh -i vm-ssh-key qemucat@qemucat.local "nm -gU /opt/local/lib/libGL.1.dylib.mesa 2>/dev/null | grep ' T _gl' | sed 's/.* _//' | grep -E '^gl[A-Z]' | grep -v '^glX' | sort -u")

if [ -z "$SYMBOLS" ]; then
    echo "❌ Failed to extract symbols from VM"
    exit 1
fi

SYMBOL_COUNT=$(echo "$SYMBOLS" | wc -l | tr -d ' ')
echo "✅ Found $SYMBOL_COUNT OpenGL functions"

# Generate C stub file
OUTPUT_FILE="SharedGL/metal/gl_stubs_generated.c"
echo "📝 Generating stubs to $OUTPUT_FILE..."

cat > "$OUTPUT_FILE" << 'HEADER_EOF'
//
// Auto-generated OpenGL function stubs
// These forward all OpenGL calls to Mesa's libGL
//
// Generated by generate_gl_stubs.sh
//

#include <dlfcn.h>
#include <stdio.h>

// Forward declaration of load_original_libgl() from glx_wrapper.c
extern void* original_libgl;
extern void load_original_libgl(void);

// Generic stub that forwards any function call
// Uses libffi-style approach: just dlsym and cast
#define STUB_FUNCTION(name) \
    void* name() { \
        static void* fn = NULL; \
        if (!fn) { \
            load_original_libgl(); \
            if (original_libgl) { \
                fn = dlsym(original_libgl, #name); \
            } \
        } \
        if (!fn) return NULL; \
        /* This is unsafe but works for most cases - proper solution needs libffi */ \
        void* (*func)() = fn; \
        return func(); \
    }

// OpenGL function stubs (auto-generated)
HEADER_EOF

# Generate stub for each symbol
echo "$SYMBOLS" | while read symbol; do
    echo "STUB_FUNCTION($symbol)" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"
echo "// End of auto-generated stubs" >> "$OUTPUT_FILE"

echo "✅ Generated $SYMBOL_COUNT function stubs"
echo ""
echo "⚠️  NOTE: These stubs use unsafe function pointer casting."
echo "   They work for simple functions but may fail for complex signatures."
echo "   For production, use libffi or proper function signatures."
echo ""
echo "Next step: Compile glx_wrapper.c with gl_stubs_generated.c"
